version: "3"

services:
  pg-tasks:
    container_name: pg-tasks
    image: postgres:9
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_PASSWORD=password

  jenkins-tasks:
    container_name: jenkins-tasks
    image: jenkins/jenkins:lts-jdk8
    ports:
      - 8080:8080
      - 50000:50000
    restart: on-failure
    volumes:
      - ./jenkins_home:/var/jenkins_home

